export const CAPABILITIES = [
	'clients.read',
	'clients.manage',
	'users.manage',
	'audit.read',
	'knowledge.read',
	'knowledge.manage',
	'pages.read',
	'pages.manage',
	'launch.read',
	'launch.manage',
	'leads.read',
	'leads.manage',
	'analytics.read',
	'email.read',
	'email.manage',
	'social.read',
	'social.manage',
	'seo.read',
	'seo.manage',
	'experiments.read',
	'experiments.manage',
	'ai.read',
	'ai.manage',
	'scale.read',
	'scale.manage',
	'goals.read',
	'goals.manage',
	'control.operator'
] as const;

export type Capability = (typeof CAPABILITIES)[number];

/** Operator Control cockpit. Client roles omit this; grant it to expand a client user. */
export const OPERATOR_CONTROL_NAV_CAPABILITY = 'control.operator' satisfies Capability;

export const ROLE_KEYS = [
	'mge_super_admin',
	'mge_operator',
	'client_owner',
	'client_admin',
	'read_only'
] as const;

export type RoleKey = (typeof ROLE_KEYS)[number];

export const ROLE_CAPABILITIES: Record<RoleKey, Capability[]> = {
	mge_super_admin: [
		'clients.read',
		'clients.manage',
		'users.manage',
		'audit.read',
		'knowledge.read',
		'knowledge.manage',
		'pages.read',
		'pages.manage',
		'launch.read',
		'launch.manage',
		'leads.read',
		'leads.manage',
		'analytics.read',
		'email.read',
		'email.manage',
		'social.read',
		'social.manage',
		'seo.read',
		'seo.manage',
		'experiments.read',
		'experiments.manage',
		'ai.read',
		'ai.manage',
		'scale.read',
		'scale.manage',
		'goals.read',
		'goals.manage',
		'control.operator'
	],
	mge_operator: [
		'clients.read',
		'clients.manage',
		'users.manage',
		'audit.read',
		'knowledge.read',
		'knowledge.manage',
		'pages.read',
		'pages.manage',
		'launch.read',
		'launch.manage',
		'leads.read',
		'leads.manage',
		'analytics.read',
		'email.read',
		'email.manage',
		'social.read',
		'social.manage',
		'seo.read',
		'seo.manage',
		'experiments.read',
		'experiments.manage',
		'ai.read',
		'ai.manage',
		'scale.read',
		'scale.manage',
		'goals.read',
		'goals.manage',
		'control.operator'
	],
	client_owner: [
		'clients.read',
		'users.manage',
		'audit.read',
		'knowledge.read',
		'knowledge.manage',
		'pages.read',
		'pages.manage',
		'launch.read',
		'launch.manage',
		'leads.read',
		'leads.manage',
		'analytics.read',
		'email.read',
		'email.manage',
		'social.read',
		'social.manage',
		'seo.read',
		'seo.manage',
		'experiments.read',
		'experiments.manage',
		'ai.read',
		'ai.manage',
		'scale.read',
		'goals.read',
		'goals.manage'
	],
	client_admin: [
		'clients.read',
		'users.manage',
		'knowledge.read',
		'knowledge.manage',
		'pages.read',
		'pages.manage',
		'launch.read',
		'launch.manage',
		'leads.read',
		'leads.manage',
		'analytics.read',
		'email.read',
		'email.manage',
		'social.read',
		'social.manage',
		'seo.read',
		'seo.manage',
		'experiments.read',
		'experiments.manage',
		'ai.read',
		'ai.manage',
		'scale.read',
		'goals.read',
		'goals.manage'
	],
	read_only: [
		'clients.read',
		'audit.read',
		'knowledge.read',
		'pages.read',
		'launch.read',
		'leads.read',
		'analytics.read',
		'email.read',
		'social.read',
		'seo.read',
		'experiments.read',
		'ai.read',
		'scale.read',
		'goals.read'
	]
};
